name: basemap
channels:
- scitools
- obspy
- conda-forge
- defaults
dependencies:
- basemap=1.1.0=py36_2
- basemap-data-hires
- bleach=2.0.0=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- freetype=2.7=1
- geos=3.5.1=1
- html5lib=0.999999999=py36_0
- icu=58.1=1
- ipykernel=4.6.1=py36_0
- ipython=6.2.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.1=py_2
- jedi=0.10.2=py36_0
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libpng=1.6.28=0
- libsodium=1.0.10=0
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=py36_2
- mistune=0.7.4=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- notebook=5.1.0=py36_0
- obspy
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyproj=1.9.5.1=py36_0
- pyqt=5.6.0=py36_4
- pyshp=1.2.12=py_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.3.1=py36_0
- readline=6.2=0
- setuptools=36.3.0=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- sqlite=3.13.0=1
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.19=2
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0
- widgetsnbextension=3.0.3
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15

