name: python_for_scientists
channels:
- conda
- defaults
dependencies:
- backports.shutil_get_terminal_size=1.0.0=py35_0
- basemap=1.0.8.dev0=np111py35_2
- basemap-data-hires=1.0.8.dev0=1
- blas=1.1=openblas
- ca-certificates=2016.9.26=0
- cairo=1.12.18=8
- certifi=2016.9.26=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- fontconfig=2.11.1=3
- freetype=2.6.3=1
- geos=3.4.2=2
- gettext=0.19.7=1
- glib=2.48.0=4
- harfbuzz=1.0.6=0
- icu=56.1=4
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_2
- jinja2=2.8=py35_1
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- libffi=3.2.1=2
- libiconv=1.14=3
- libpng=1.6.26=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- libxml2=2.9.4=3
- markupsafe=0.23=py35_0
- matplotlib=1.5.3=np111py35_2
- mistune=0.7.3=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- ncurses=5.9=9
- notebook=4.2.3=py35_0
- numpy=1.11.2=py35_blas_openblas_200
- openblas=0.2.18=6
- openssl=1.0.2h=2
- pandas=0.19.1=np111py35_0
- pango=1.40.1=0
- pcre=8.38=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=9.0.1=py35_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_1
- pyparsing=2.1.10=py35_0
- pyproj=1.9.5.1=py35_0
- pyqt=4.11.4=py35_1
- pyshp=1.2.10=py35_0
- python=3.5.2=2
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- pyzmq=15.4.0=py35_0
- qt=4.8.7=3
- qtconsole=4.2.1=py35_0
- readline=6.2=0
- scipy=0.18.1=np111py35_blas_openblas_200
- setuptools=28.8.0=py35_0
- shapely=1.5.17=np111py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_1
- sqlite=3.13.0=1
- terminado=0.6=py35_0
- tk=8.5.19=0
- tornado=4.4.2=py35_0
- traitlets=4.3.0=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_3
- xz=5.2.2=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- jupyter=1.0.0=py35_3
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - basemap==1.0.8
  - certifi==2016.9.26
  - cycler==0.10.0
  - decorator==4.0.10
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - markupsafe==0.23
  - matplotlib==1.5.3
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - notebook==4.2.3
  - numpy==1.11.2
  - pandas==0.19.1
  - pexpect==4.2.1
  - pickleshare==0.7.3
  - pip==9.0.1
  - prompt-toolkit==1.0.9
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.10
  - pyproj==1.9.5.1
  - pyshp==1.2.10
  - python-dateutil==2.5.3
  - pytz==2016.7
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - scipy==0.18.1
  - setuptools==28.8.0.post20161110
  - shapely==1.5.17
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - tornado==4.4.2
  - traitlets==4.3.0
  - wcwidth==0.1.7
  - wheel==0.29.0
  - widgetsnbextension==1.2.6
